# Generated by Django 3.2.3 on 2021-05-16 14:27

from django.db import migrations, models
import django.db.models.deletion
import django_thumbs.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_thumbs.fields.ImageThumbsField(blank=True, null=True, sizes=({'code': '150', 'wxh': '150x150'},), upload_to='pets')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='image url')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6)),
                ('for_adoption', models.BooleanField(default=False, verbose_name='for adoption')),
                ('years', models.SmallIntegerField(verbose_name='years')),
                ('months', models.SmallIntegerField(verbose_name='months')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='price')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pets.breed', verbose_name='breed')),
            ],
        ),
        migrations.AddField(
            model_name='breed',
            name='specie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.specie', verbose_name='name'),
        ),
    ]
